from __future__ import annotations

from typing import Any

# Curated public resources. These links are intentionally deterministic and are
# never generated by the language model.
GENERAL_DIRECTORY = {
    "title": "Metro Public Health Community Resource Directory",
    "description": "Browse Nashville services for basic needs, health, housing, jobs, family support, and more.",
    "url": "https://metro-public-health-community-resource-directory-nashville.hub.arcgis.com/",
}

RESOURCE_LIBRARY: dict[str, dict[str, str]] = {
    "food": {
        "title": "Second Harvest Food Finder",
        "description": "Search food distribution sites, mobile pantries, and benefit-support resources by location.",
        "url": "https://www.secondharvestmidtn.org/find-resources/find-food/",
    },
    "quitline": {
        "title": "Tennessee Tobacco QuitLine",
        "description": "Find free, confidential coaching and tools for Tennesseans who want to quit tobacco.",
        "url": "https://www.tn.gov/health/tupcp.html",
    },
    "redline": {
        "title": "Tennessee REDLINE",
        "description": "Find confidential referrals for substance-use treatment and recovery support across Tennessee.",
        "url": "https://www.tn.gov/behavioral-health/substance-abuse-services/prevention/tennessee-redline.html",
    },
    "parks": {
        "title": "Nashville Parks and Recreation Classes",
        "description": "Explore local fitness, recreation, nature, and activity options offered across Nashville.",
        "url": "https://www.nashville.gov/departments/parks/classes",
    },
    "clinics": {
        "title": "Metro Public Health Clinic Locations",
        "description": "Review public health center locations and available preventive health services.",
        "url": "https://www.nashville.gov/departments/health/clinic-locations",
    },
    "health_services": {
        "title": "Metro Public Health Department Services",
        "description": "Explore Nashville public-health programs, clinics, behavioral-health services, and community resources.",
        "url": "https://www.nashville.gov/departments/health/services",
    },
    "behavioral_health": {
        "title": "Metro Public Health Behavioral Health Services",
        "description": "Learn about local behavioral-health services and prevention resources available through Metro Health.",
        "url": "https://www.nashville.gov/departments/health",
    },
    "environment": {
        "title": "Metro Environmental Health Programs",
        "description": "Learn about local programs related to clean air, safe food, and healthy living conditions.",
        "url": "https://www.nashville.gov/departments/health/environmental-health",
    },
    "tn211": {
        "title": "Tennessee 211 Resource Search",
        "description": "Search for local help with food, housing, utilities, transportation, health care, and other needs.",
        "url": "https://tn211.myresourcedirectory.com/",
    },
}

INDICATOR_RESOURCES: dict[str, list[str]] = {
    "Food Insecurity": ["food", "tn211"],
    "Adult Smoking": ["quitline", "health_services"],
    "Drug Overdose Deaths": ["redline", "behavioral_health"],
    "Poor Mental Health Days": ["behavioral_health", "tn211"],
    "Suicide Rate": ["behavioral_health", "tn211"],
    "Mental Health Providers": ["behavioral_health", "tn211"],
    "Physical Inactivity": ["parks", "health_services"],
    "Access to Exercise Opportunities": ["parks", "health_services"],
    "Adult Obesity": ["parks", "health_services"],
    "Diabetes Prevalence": ["health_services", "parks"],
    "Uninsured": ["clinics", "tn211"],
    "Primary Care Physicians": ["clinics", "tn211"],
    "Preventable Hospital Stays": ["clinics", "health_services"],
    "Infant Mortality": ["clinics", "health_services"],
    "Teen Birth Rate": ["clinics", "health_services"],
    "Severe Housing Problems": ["tn211", "directory"],
    "Severe Housing Cost Burden": ["tn211", "directory"],
    "Children in Poverty": ["directory", "tn211"],
    "Unemployment": ["directory", "tn211"],
    "Median Household Income": ["directory", "tn211"],
    "Income Inequality": ["directory", "tn211"],
    "Broadband Access": ["directory", "tn211"],
    "High School Completion": ["directory", "tn211"],
    "Air Pollution – Particulate Matter": ["environment", "health_services"],
}


def resources_for(indicator: str, category: str = "") -> list[dict[str, Any]]:
    keys = INDICATOR_RESOURCES.get(indicator, [])
    if not keys:
        if category == "Clinical care":
            keys = ["clinics", "directory"]
        elif category == "Health behaviors":
            keys = ["health_services", "directory"]
        elif category == "Physical environment":
            keys = ["directory", "tn211"]
        else:
            keys = ["directory"]

    results: list[dict[str, Any]] = []
    for key in keys[:2]:
        resource = GENERAL_DIRECTORY if key == "directory" else RESOURCE_LIBRARY.get(key)
        if resource:
            results.append(dict(resource))
    return results
